version: '3.8'

services:
  backend:
    build:
      context: .  # Root directory as context
      dockerfile: ./backend/Dockerfile  # Path to backend Dockerfile
    container_name: mern-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern-network

  frontend:
    build:
      context: .  # Root directory as context
      dockerfile: ./frontend/Dockerfile  # Path to frontend Dockerfile
    container_name: mern-frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://mern-backend:3000/api
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
