# Docker Compose file for MERN Stack
services:
  # MongoDB Database
  mongo:
    image: mongo:6
    container_name: expense-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=expense_tracker
    networks:
      - expense-network

  # Backend (Node.js/Express API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/expense_tracker
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - expense-network

  # Frontend (React with Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - expense-network

# Docker networks
networks:
  expense-network:
    driver: bridge

# Docker volumes
volumes:
  mongo-data: