apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-backend
  labels:
    app: expenses-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-backend
  template:
    metadata:
      labels:
        app: expenses-backend
    spec:
      containers:
      - name: expenses-backend
        image: krishna1908/expense-tracker-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection_string
        volumeMounts:
        - name: backend-data
          mountPath: /app/data
      volumes:
      - name: backend-data
        persistentVolumeClaim:
          claimName: backend-pvc
---
# PersistentVolumeClaim for Backend
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Secret for MongoDB Atlas credentials
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  connection_string: "mongodb://test-19:RLVegcPerbkmPUsS@cluster0-shard-00-00.pfmsb.mongodb.net:27017,cluster0-shard-00-01.pfmsb.mongodb.net:27017,cluster0-shard-00-02.pfmsb.mongodb.net:27017/?replicaSet=atlas-12cbxq-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=Cluster0"