apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-frontend
  labels:
    app: expenses-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-frontend
  template:
    metadata:
      labels:
        app: expenses-frontend
    spec:
      containers:
      - name: expenses-frontend
        image: expense-tracker-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173  # Fixed: Should match Dockerfile EXPOSE 80
        env:
        - name: VITE_API_URL
          value: "http://expenses-backend-service:3000/api"
        volumeMounts:
        - name: frontend-data
          mountPath: /app/data
      volumes:
      - name: frontend-data
        persistentVolumeClaim:
          claimName: frontend-pvc
---
# PersistentVolumeClaim for Frontend
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi